language: java
dist: trusty
jdk:
- openjdk8
- oraclejdk8
- oraclejdk9
- oraclejdk11
notifications:
  email:
  - mdr-eng@google.com
after_success:
- "./gradlew jacocoTestReport coveralls"
env:
  global:
  - secure: TOW8DiUzKHdpa/ZL9yaAvzvzAsTfJ6+bW4y2JfukpLT4Qj0V6e6fFPlBwfOvGYR9NAGLpw7DxdNJcSn1sTxIdwvwm5YkriMoSNpHh7IMUs9vx5d/k9ZwR4RQ+XyVzm3oskoxOZUX3HnKvP3nJkGvLgTxsDBJw4FcpuU9V4yTEK4=
  - secure: JyoUWkUDIR8O6Fm0QAzmb67OqlMceExmu6GJG2Z/zNSELr8t0mkvKkZ9ApQ0rUxkimUdc5SDY541DCGbwDzmp4ZE1Jd47olq0YJNSUqFvNmdmGZOM+aUfN5jREl9c4R4XPw4GxFhjym8GUPXQTOjxV18nqPyt6aJxN8sq4062u0=
  - secure: EhTBrng1AmJGXZ02R5b2txc4LXIsdHuDQ24Wt5IBHT+2011IeG/dKvnygyxplWxZiCFyoPrP6AIwZcgil6fWm0DoSBOcZ0SAFUXMRnqOM/1vFICWNy2nRqH1aRy/HTgRoLA+VYcyypwVfMNbgbV2ZKR/cmDOUcZBJWbuuoiqW80=
  - secure: YBx2DnYdeV/Y7HJXneJ5EwzNI0qf8YqEFnBy2ZTiFn9T8kfGmaJ8yQi99JV9g8BPXELnExPwxuo5W1uGecrPZvh0StHOScAxP0OHC1tgahgE7ziow49I+QmlO6c5FOcCQxDks70MiiwcsdvE91KUqE0sjWJmurcIrkGs4hYM0zs=
  - secure: RvI62yA7y8ByDJZyVjuZP4krWJtWLwHglhCgw/md01oPAR0xiCH/2osuJVNc3UaUyYQly4novXk1+8cA7HuvoflkzGXdAsnN+PFA1J/XredKAaufOKstKWKXki9ejcJsGH177Ny2b0N7vadDFB9s6Xj1H74CqYEh/uNmvK72N7M=
  - secure: INA/3Gkoh5O9orGfxNhnLOTyJdNO7TlyQCjCA2As7dh0if0OZMha1bMWZQGTPfkczlL1tJVrFhNAJL13VyGuQdjrUTRrGQVHLiKgiog4JzNLBVzUL+HdrFEuU49JonnAQdmfzZDw4N0Z8iOPncOdxSI6kHtXibY2/IWUWQmdw3M=
deploy:
  provider: script
  script: openssl aes-256-cbc -K $encrypted_e022d974387b_key -iv $encrypted_e022d974387b_iv
    -in .travis.gpg.enc -out .travis.gpg -d && ./gradlew publishToSonatype -PsonatypeUsername=${SONATYPE_USERNAME}
    -PsonatypePassword=${SONATYPE_PASSWORD} -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE}
    -Psigning.secretKeyRingFile=.travis.gpg --info
  on:
    tags: true
    jdk: openjdk8
