language: java
jdk:
- oraclejdk7
- openjdk7
notifications:
  email:
  - mdr-eng@google.com
env:
  matrix:
  - secure: deyC4cKGt3/uHxSDSIBLu/8Uq5r0hodKdNXbibXfqjWdq3K2gmGJjW/9ev40CygYnZFELNWL5S5oJ1RYdxCYKv6ft+xjBHgaQtcK6zpFCBMOfJBbZ64XtsJN1mTwJQ+RpPTsdgRKa6OqL5oPppJZYWu+rShotG94/5Yy/rc/ots=
  - secure: IMZrxRq7pyYXPnPpYVwQzhFfX953uBHddQEZ/HAb0yxLs2vtE6rOfoQSmNP9Sv8pyuWx1vld+W5+4z79Fb/aONaLGjhcweRA1vVh3WVi7ItBj8+8W0I6TLlE48kMAFPdhR4kQLyAuTkIr+qjIhAgoYd1IS11wIcEBC1sB/FnR+M=
